const seminars = [
  {
    seminarId : 2,
    seminarName : "2022-08-29",
    sortedSeminarAttendances:[
      {
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 14,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석 전",
        absenceExcuse: null,
        memberId: 15,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 16,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 17,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 18,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 19,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 20,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 21,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 22,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 23,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 24,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 25,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 26,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 27,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 28,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 29,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 30,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 31,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 32,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 33,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 34,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 35,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 36,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 37,
      },
    ]
  },{
    seminarId : 2,
    seminarName : "2022-08-29",
    sortedSeminarAttendances:[
      {
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 14,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 15,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 16,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 17,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 18,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 19,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 20,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 21,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 22,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 23,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 24,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 25,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 26,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 27,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 28,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 29,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 30,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 31,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 32,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 33,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 34,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 35,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 36,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 37,
      },
    ]
  }, {
    seminarId : 2,
    seminarName : "2022-08-29",
    sortedSeminarAttendances:[
      {
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 14,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 15,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 16,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 17,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 18,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 19,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 20,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 21,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 22,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 23,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 24,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 25,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 26,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 27,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 28,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 29,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 30,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 31,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 32,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 33,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 34,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 35,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 36,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 37,
      },
    ]
  }, {
    seminarId : 2,
    seminarName : "2022-08-29",
    sortedSeminarAttendances:[
      {
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 14,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 15,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 16,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 17,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 18,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 19,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 20,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 21,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 22,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 23,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 24,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 25,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 26,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 27,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 28,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 29,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 30,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 31,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 32,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 33,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 34,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 35,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 36,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 37,
      },
    ]
  }, {
    seminarId : 2,
    seminarName : "2022-08-29",
    sortedSeminarAttendances:[
      {
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 14,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 15,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 16,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 17,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 18,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 19,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 20,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 21,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 22,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 23,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 24,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 25,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 26,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 27,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 28,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 29,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 30,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 31,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 32,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 33,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 34,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 35,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 36,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 37,
      },
    ]
  }, {
    seminarId : 2,
    seminarName : "2022-08-29",
    sortedSeminarAttendances:[
      {
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 14,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 15,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 16,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 17,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 18,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 19,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 20,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 21,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 22,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 23,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 24,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 25,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 26,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 27,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 28,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 29,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 30,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 31,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 32,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 33,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 34,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 35,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 36,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 37,
      },
    ]
  }, {
    seminarId : 2,
    seminarName : "2022-08-29",
    sortedSeminarAttendances:[
      {
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 14,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 15,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 16,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 17,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 18,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 19,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 20,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 21,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 22,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 23,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 24,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 25,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 26,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 27,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 28,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 29,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 30,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 31,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 32,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 33,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 34,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 35,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 36,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 37,
      },
    ]
  }, {
    seminarId : 2,
    seminarName : "2022-08-29",
    sortedSeminarAttendances:[
      {
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 14,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 15,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 16,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 17,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 18,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 19,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 20,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 21,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 22,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 23,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 24,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 25,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 26,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 27,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 28,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 29,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 30,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 31,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 32,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 33,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 34,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 35,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 36,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 37,
      },
    ]
  }, {
    seminarId : 2,
    seminarName : "2022-08-29",
    sortedSeminarAttendances:[
      {
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 14,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 15,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 16,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 17,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 18,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 19,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 20,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 21,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 22,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 23,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 24,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 25,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 26,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 27,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 28,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 29,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 30,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 31,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 32,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 33,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 34,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 35,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 36,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 37,
      },
    ]
  }, {
    seminarId : 2,
    seminarName : "2022-08-29",
    sortedSeminarAttendances:[
      {
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 14,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 15,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 16,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 17,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 18,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 19,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 20,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 21,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 22,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 23,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 24,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 25,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 26,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 27,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 28,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 29,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 30,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 31,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 32,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 33,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 34,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 35,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 36,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 37,
      },
    ]
  }, {
    seminarId : 2,
    seminarName : "2022-08-29",
    sortedSeminarAttendances:[
      {
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 14,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 15,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 16,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 17,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 18,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 19,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 20,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 21,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 22,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 23,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 24,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 25,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 26,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 27,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 28,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 29,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 30,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 31,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 32,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 33,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 34,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 35,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 36,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 37,
      },
    ]
  }, {
    seminarId : 2,
    seminarName : "2022-08-29",
    sortedSeminarAttendances:[
      {
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 14,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 15,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 16,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 17,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 18,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 19,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 20,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 21,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 22,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 23,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 24,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 25,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 26,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 27,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 28,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 29,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 30,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 31,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 32,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 33,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 34,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 35,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 36,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 37,
      },
    ]
  }, {
    seminarId : 2,
    seminarName : "2022-08-29",
    sortedSeminarAttendances:[
      {
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 14,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 15,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 16,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 17,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 18,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 19,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 20,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 21,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 22,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 23,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 24,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 25,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 26,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 27,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 28,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 29,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 30,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 31,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 32,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 33,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 34,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 35,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 36,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 37,
      },
    ]
  }, {
    seminarId : 2,
    seminarName : "2022-08-29",
    sortedSeminarAttendances:[
      {
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 14,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 15,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 16,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 17,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 18,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 19,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 20,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 21,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 22,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 23,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 24,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 25,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 26,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 27,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 28,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 29,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 30,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 31,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 32,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 33,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 34,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 35,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 36,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 37,
      },
    ]
  }, {
    seminarId : 2,
    seminarName : "2022-08-29",
    sortedSeminarAttendances:[
      {
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 14,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 15,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 16,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 17,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 18,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 19,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 20,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 21,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 22,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 23,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 24,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 25,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 26,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 27,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 28,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 29,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 30,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 31,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 32,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 33,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 34,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 35,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 36,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 37,
      },
    ]
  }, {
    seminarId : 2,
    seminarName : "2022-08-29",
    sortedSeminarAttendances:[
      {
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 14,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 15,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 16,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 17,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 18,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 19,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 20,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 21,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 22,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 23,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 24,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 25,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 26,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 27,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 28,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 29,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 30,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 31,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 32,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 33,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 34,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 35,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 36,
      },{
        attendanceId: 1,
        generation: 11,
        memberName: "pipi00",
        attendanceStatusType: "출석",
        absenceExcuse: null,
        memberId: 37,
      },
    ]
  }, 
];

const userttt = [
  {
    memberId: 14,
    realName: "pipi00",
    generation: 11,
  },{
    memberId: 15,
    realName: "pipi00",
    generation: 12,
  },{
    memberId: 16,
    realName: "pipi00",
    generation: 13,
  },{
    memberId: 17,
    realName: "pipi00",
    generation: 14,
  },{
    memberId: 18,
    realName: "pipi00",
    generation: 15,
  },{
    memberId: 19,
    realName: "pipi00",
    generation: 11,
  },{
    memberId: 20,
    realName: "pipi00",
    generation: 11,
  },{
    memberId: 21,
    realName: "pipi00",
    generation: 11,
  },{
    memberId: 22,
    realName: "pipi00",
    generation: 11,
  },{
    memberId: 23,
    realName: "pipi00",
    generation: 11,
  },{
    memberId: 24,
    realName: "pipi00",
    generation: 11,
  },{
    memberId: 25,
    realName: "pipi00",
    generation: 11,
  },{
    memberId: 26,
    realName: "pipi00",
    generation: 11,
  },{
    memberId: 27,
    realName: "pipi00",
    generation: 11,
  },{
    memberId: 28,
    realName: "pipi00",
    generation: 11,
  },{
    memberId: 29,
    realName: "pipi00",
    generation: 11,
  },{
    memberId: 30,
    realName: "pipi00",
    generation: 11,
  },{
    memberId: 31,
    realName: "pipi00",
    generation: 11,
  },{
    memberId: 32,
    realName: "pipi00",
    generation: 11,
  },{
    memberId: 33,
    realName: "pipi00",
    generation: 11,
  },{
    memberId: 34,
    realName: "pipi00",
    generation: 11,
  },{
    memberId: 35,
    realName: "pipi00",
    generation: 11,
  },{
    memberId: 36,
    realName: "pipi00",
    generation: 11,
  },{
    memberId: 37,
    realName: "pipi00",
    generation: 11,
  },{
    memberId: 34,
    realName: "pipi00",
    generation: 11,
  },{
    memberId: 35,
    realName: "pipi00",
    generation: 11,
  },{
    memberId: 36,
    realName: "pipi00",
    generation: 11,
  },{
    memberId: 37,
    realName: "pipi00",
    generation: 11,
  },{
    memberId: 36,
    realName: "pipi00",
    generation: 11,
  },{
    memberId: 37,
    realName: "pipi00",
    generation: 11,
  },{
    memberId: 37,
    realName: "pipi00",
    generation: 11,
  },
]

export { seminars, userttt };