name: Keeper Homepage Front CI/CD

on:
  push:
    branches: [ main, develop ]

jobs:
  DEV_Deploy:
    if: contains(github.ref, 'develop')
    runs-on: ubuntu-18.04
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'

      - name: Create ENV File
        run: |
          touch .env
          echo "${{ secrets.DEV_ENV }}" >> .env

      - name: Build
        run: |
          npm i --force
          CI= npm run build

      - name: Compress
        run: tar -zcvf $(date +%Y%m%d).tar.gz build

      - name: Upload to S3
        run: |
          aws s3 mv --region ap-northeast-2 \
          $(date +%Y%m%d).tar.gz \
          ${{ secrets.S3_DEV_FRONT_LOCATION }}/$(date +%Y%m%d).tar.gz
          
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.KEY }}
          script: |
            cd ~/keeper
            ./deploy_front.sh

  PROD_Deploy:
    if: contains(github.ref, 'main')
    runs-on: ubuntu-18.04
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'

      - name: Create ENV File
        run: |
          touch .env
          echo "${{ secrets.PROD_ENV }}" >> .env

      - name: Build
        run: |
          npm i
          CI= npm run build

      - name: Compress
        run: tar -zcvf $(date +%Y%m%d).tar.gz build

      - name: Upload to S3
        run: |
          aws s3 mv --region ap-northeast-2 \
          $(date +%Y%m%d).tar.gz \
          ${{ secrets.S3_PROD_FRONT_LOCATION }}/$(date +%Y%m%d).tar.gz
          
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_PROD }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.KEY_PROD }}
          script: |
            cd ~/keeper
            ./deploy_front.sh
